[workspace]
members = [
    "crates/cortex-core",
    "crates/cortex-api",
    "crates/cortex-evict",
    "crates/cortex-metrics",
    "crates/cortexd",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
publish = false
