[package]
name = "cortexd"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-core = { path = "../cortex-core" }
cortex-api = { path = "../cortex-api" }
cortex-evict = { path = "../cortex-evict" }
cortex-metrics = { path = "../cortex-metrics" }
